@host=http://localhost:3000

GET {{host}} http/1.1

### Register
POST {{host}}/register http/1.1
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "user1"
}

### Login
POST {{host}}/login http/1.1
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "user1"
}

### Post Investment
POST {{host}}/investments http/1.1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI1NzQ0MzczfQ.8G0G_mkjCkd_BalRwHJ89UR6L-kAkqlWkdfFzS-uGlI

{
    "name": "DOGE",
    "price": 200000
}

### Get Investment
GET {{host}}/investments http/1.1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI1NzQ0MzczfQ.8G0G_mkjCkd_BalRwHJ89UR6L-kAkqlWkdfFzS-uGlI

### Delete Investment
DELETE {{host}}/investments/2 http/1.1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI1NzQ0MzczfQ.8G0G_mkjCkd_BalRwHJ89UR6L-kAkqlWkdfFzS-uGlI

### Get Crypto Prices
GET {{host}}/investments/crypto http/1.1
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI1NzQ0MzczfQ.8G0G_mkjCkd_BalRwHJ89UR6L-kAkqlWkdfFzS-uGlI

